#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wed_Spa_Pro")]
public partial class DataContentDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUser_Log(User_Log instance);
  partial void UpdateUser_Log(User_Log instance);
  partial void DeleteUser_Log(User_Log instance);
  partial void InsertEmployee(Employee instance);
  partial void UpdateEmployee(Employee instance);
  partial void DeleteEmployee(Employee instance);
  partial void InsertService(Service instance);
  partial void UpdateService(Service instance);
  partial void DeleteService(Service instance);
  partial void InsertProduct(Product instance);
  partial void UpdateProduct(Product instance);
  partial void DeleteProduct(Product instance);
  partial void InsertSolution(Solution instance);
  partial void UpdateSolution(Solution instance);
  partial void DeleteSolution(Solution instance);
  partial void InsertNew(New instance);
  partial void UpdateNew(New instance);
  partial void DeleteNew(New instance);
  #endregion
	
	public DataContentDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["wed_Spa_ProConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataContentDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataContentDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataContentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataContentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<User_Log> User_Logs
	{
		get
		{
			return this.GetTable<User_Log>();
		}
	}
	
	public System.Data.Linq.Table<Employee> Employees
	{
		get
		{
			return this.GetTable<Employee>();
		}
	}
	
	public System.Data.Linq.Table<Service> Services
	{
		get
		{
			return this.GetTable<Service>();
		}
	}
	
	public System.Data.Linq.Table<Product> Products
	{
		get
		{
			return this.GetTable<Product>();
		}
	}
	
	public System.Data.Linq.Table<Solution> Solutions
	{
		get
		{
			return this.GetTable<Solution>();
		}
	}
	
	public System.Data.Linq.Table<New> News
	{
		get
		{
			return this.GetTable<New>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Log")]
public partial class User_Log : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _Functions;
	
	private string _ItemID;
	
	private string _UserID;
	
	private string _UserName;
	
	private string _Creater;
	
	private string _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnFunctionsChanging(string value);
    partial void OnFunctionsChanged();
    partial void OnItemIDChanging(string value);
    partial void OnItemIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnCreaterChanging(string value);
    partial void OnCreaterChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    #endregion
	
	public User_Log()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Functions", DbType="NVarChar(50)")]
	public string Functions
	{
		get
		{
			return this._Functions;
		}
		set
		{
			if ((this._Functions != value))
			{
				this.OnFunctionsChanging(value);
				this.SendPropertyChanging();
				this._Functions = value;
				this.SendPropertyChanged("Functions");
				this.OnFunctionsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="VarChar(14)")]
	public string ItemID
	{
		get
		{
			return this._ItemID;
		}
		set
		{
			if ((this._ItemID != value))
			{
				this.OnItemIDChanging(value);
				this.SendPropertyChanging();
				this._ItemID = value;
				this.SendPropertyChanged("ItemID");
				this.OnItemIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(30)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creater", DbType="VarChar(10)")]
	public string Creater
	{
		get
		{
			return this._Creater;
		}
		set
		{
			if ((this._Creater != value))
			{
				this.OnCreaterChanging(value);
				this.SendPropertyChanging();
				this._Creater = value;
				this.SendPropertyChanged("Creater");
				this.OnCreaterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(14)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employees")]
public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Id;
	
	private string _EmployeeName;
	
	private System.Nullable<char> _RoleId;
	
	private string _Username;
	
	private string _Password;
	
	private string _Creater;
	
	private string _CreateDate;
	
	private string _Modifier;
	
	private string _ModifyDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnRoleIdChanging(System.Nullable<char> value);
    partial void OnRoleIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCreaterChanging(string value);
    partial void OnCreaterChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnModifierChanging(string value);
    partial void OnModifierChanged();
    partial void OnModifyDateChanging(string value);
    partial void OnModifyDateChanged();
    #endregion
	
	public Employee()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(100)")]
	public string EmployeeName
	{
		get
		{
			return this._EmployeeName;
		}
		set
		{
			if ((this._EmployeeName != value))
			{
				this.OnEmployeeNameChanging(value);
				this.SendPropertyChanging();
				this._EmployeeName = value;
				this.SendPropertyChanged("EmployeeName");
				this.OnEmployeeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Char(1)")]
	public System.Nullable<char> RoleId
	{
		get
		{
			return this._RoleId;
		}
		set
		{
			if ((this._RoleId != value))
			{
				this.OnRoleIdChanging(value);
				this.SendPropertyChanging();
				this._RoleId = value;
				this.SendPropertyChanged("RoleId");
				this.OnRoleIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creater", DbType="VarChar(10)")]
	public string Creater
	{
		get
		{
			return this._Creater;
		}
		set
		{
			if ((this._Creater != value))
			{
				this.OnCreaterChanging(value);
				this.SendPropertyChanging();
				this._Creater = value;
				this.SendPropertyChanged("Creater");
				this.OnCreaterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(14)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifier", DbType="VarChar(10)")]
	public string Modifier
	{
		get
		{
			return this._Modifier;
		}
		set
		{
			if ((this._Modifier != value))
			{
				this.OnModifierChanging(value);
				this.SendPropertyChanging();
				this._Modifier = value;
				this.SendPropertyChanged("Modifier");
				this.OnModifierChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="VarChar(14)")]
	public string ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Services")]
public partial class Service : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Id;
	
	private string _Header;
	
	private string _Name;
	
	private string _Descrition;
	
	private string _Price;
	
	private System.Nullable<char> _Type_Services;
	
	private string _Link_Image_Small;
	
	private string _Link_Image;
	
	private string _Creater;
	
	private string _CreateDate;
	
	private string _Modifier;
	
	private string _ModifyDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnHeaderChanging(string value);
    partial void OnHeaderChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescritionChanging(string value);
    partial void OnDescritionChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnType_ServicesChanging(System.Nullable<char> value);
    partial void OnType_ServicesChanged();
    partial void OnLink_Image_SmallChanging(string value);
    partial void OnLink_Image_SmallChanged();
    partial void OnLink_ImageChanging(string value);
    partial void OnLink_ImageChanged();
    partial void OnCreaterChanging(string value);
    partial void OnCreaterChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnModifierChanging(string value);
    partial void OnModifierChanged();
    partial void OnModifyDateChanging(string value);
    partial void OnModifyDateChanged();
    #endregion
	
	public Service()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Header", DbType="NVarChar(2000)")]
	public string Header
	{
		get
		{
			return this._Header;
		}
		set
		{
			if ((this._Header != value))
			{
				this.OnHeaderChanging(value);
				this.SendPropertyChanging();
				this._Header = value;
				this.SendPropertyChanged("Header");
				this.OnHeaderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrition", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Descrition
	{
		get
		{
			return this._Descrition;
		}
		set
		{
			if ((this._Descrition != value))
			{
				this.OnDescritionChanging(value);
				this.SendPropertyChanging();
				this._Descrition = value;
				this.SendPropertyChanged("Descrition");
				this.OnDescritionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="VarChar(10)")]
	public string Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Services", DbType="Char(1)")]
	public System.Nullable<char> Type_Services
	{
		get
		{
			return this._Type_Services;
		}
		set
		{
			if ((this._Type_Services != value))
			{
				this.OnType_ServicesChanging(value);
				this.SendPropertyChanging();
				this._Type_Services = value;
				this.SendPropertyChanged("Type_Services");
				this.OnType_ServicesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image_Small", DbType="NVarChar(200)")]
	public string Link_Image_Small
	{
		get
		{
			return this._Link_Image_Small;
		}
		set
		{
			if ((this._Link_Image_Small != value))
			{
				this.OnLink_Image_SmallChanging(value);
				this.SendPropertyChanging();
				this._Link_Image_Small = value;
				this.SendPropertyChanged("Link_Image_Small");
				this.OnLink_Image_SmallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image", DbType="NVarChar(200)")]
	public string Link_Image
	{
		get
		{
			return this._Link_Image;
		}
		set
		{
			if ((this._Link_Image != value))
			{
				this.OnLink_ImageChanging(value);
				this.SendPropertyChanging();
				this._Link_Image = value;
				this.SendPropertyChanged("Link_Image");
				this.OnLink_ImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creater", DbType="VarChar(10)")]
	public string Creater
	{
		get
		{
			return this._Creater;
		}
		set
		{
			if ((this._Creater != value))
			{
				this.OnCreaterChanging(value);
				this.SendPropertyChanging();
				this._Creater = value;
				this.SendPropertyChanged("Creater");
				this.OnCreaterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(14)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifier", DbType="VarChar(10)")]
	public string Modifier
	{
		get
		{
			return this._Modifier;
		}
		set
		{
			if ((this._Modifier != value))
			{
				this.OnModifierChanging(value);
				this.SendPropertyChanging();
				this._Modifier = value;
				this.SendPropertyChanged("Modifier");
				this.OnModifierChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="VarChar(14)")]
	public string ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Id;
	
	private string _Header;
	
	private string _Name;
	
	private string _Descrition;
	
	private string _Price;
	
	private System.Nullable<char> _Type_Product;
	
	private string _Link_Image_Small;
	
	private string _Link_Image;
	
	private string _Creater;
	
	private string _CreateDate;
	
	private string _Modifier;
	
	private string _ModifyDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnHeaderChanging(string value);
    partial void OnHeaderChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescritionChanging(string value);
    partial void OnDescritionChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnType_ProductChanging(System.Nullable<char> value);
    partial void OnType_ProductChanged();
    partial void OnLink_Image_SmallChanging(string value);
    partial void OnLink_Image_SmallChanged();
    partial void OnLink_ImageChanging(string value);
    partial void OnLink_ImageChanged();
    partial void OnCreaterChanging(string value);
    partial void OnCreaterChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnModifierChanging(string value);
    partial void OnModifierChanged();
    partial void OnModifyDateChanging(string value);
    partial void OnModifyDateChanged();
    #endregion
	
	public Product()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Header", DbType="NVarChar(2000)")]
	public string Header
	{
		get
		{
			return this._Header;
		}
		set
		{
			if ((this._Header != value))
			{
				this.OnHeaderChanging(value);
				this.SendPropertyChanging();
				this._Header = value;
				this.SendPropertyChanged("Header");
				this.OnHeaderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrition", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Descrition
	{
		get
		{
			return this._Descrition;
		}
		set
		{
			if ((this._Descrition != value))
			{
				this.OnDescritionChanging(value);
				this.SendPropertyChanging();
				this._Descrition = value;
				this.SendPropertyChanged("Descrition");
				this.OnDescritionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="VarChar(10)")]
	public string Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Product", DbType="Char(1)")]
	public System.Nullable<char> Type_Product
	{
		get
		{
			return this._Type_Product;
		}
		set
		{
			if ((this._Type_Product != value))
			{
				this.OnType_ProductChanging(value);
				this.SendPropertyChanging();
				this._Type_Product = value;
				this.SendPropertyChanged("Type_Product");
				this.OnType_ProductChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image_Small", DbType="NVarChar(200)")]
	public string Link_Image_Small
	{
		get
		{
			return this._Link_Image_Small;
		}
		set
		{
			if ((this._Link_Image_Small != value))
			{
				this.OnLink_Image_SmallChanging(value);
				this.SendPropertyChanging();
				this._Link_Image_Small = value;
				this.SendPropertyChanged("Link_Image_Small");
				this.OnLink_Image_SmallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image", DbType="NVarChar(200)")]
	public string Link_Image
	{
		get
		{
			return this._Link_Image;
		}
		set
		{
			if ((this._Link_Image != value))
			{
				this.OnLink_ImageChanging(value);
				this.SendPropertyChanging();
				this._Link_Image = value;
				this.SendPropertyChanged("Link_Image");
				this.OnLink_ImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creater", DbType="VarChar(10)")]
	public string Creater
	{
		get
		{
			return this._Creater;
		}
		set
		{
			if ((this._Creater != value))
			{
				this.OnCreaterChanging(value);
				this.SendPropertyChanging();
				this._Creater = value;
				this.SendPropertyChanged("Creater");
				this.OnCreaterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(14)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifier", DbType="VarChar(10)")]
	public string Modifier
	{
		get
		{
			return this._Modifier;
		}
		set
		{
			if ((this._Modifier != value))
			{
				this.OnModifierChanging(value);
				this.SendPropertyChanging();
				this._Modifier = value;
				this.SendPropertyChanged("Modifier");
				this.OnModifierChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="VarChar(14)")]
	public string ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Solutions")]
public partial class Solution : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _Header;
	
	private string _Contents;
	
	private System.Nullable<char> _Type_Solution;
	
	private string _Link_Image_Small;
	
	private string _Link_Image;
	
	private string _Poster;
	
	private string _PosterID;
	
	private string _Creater;
	
	private string _CreateDate;
	
	private string _Modifier;
	
	private string _ModifyDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnHeaderChanging(string value);
    partial void OnHeaderChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnType_SolutionChanging(System.Nullable<char> value);
    partial void OnType_SolutionChanged();
    partial void OnLink_Image_SmallChanging(string value);
    partial void OnLink_Image_SmallChanged();
    partial void OnLink_ImageChanging(string value);
    partial void OnLink_ImageChanged();
    partial void OnPosterChanging(string value);
    partial void OnPosterChanged();
    partial void OnPosterIDChanging(string value);
    partial void OnPosterIDChanged();
    partial void OnCreaterChanging(string value);
    partial void OnCreaterChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnModifierChanging(string value);
    partial void OnModifierChanged();
    partial void OnModifyDateChanging(string value);
    partial void OnModifyDateChanged();
    #endregion
	
	public Solution()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Header", DbType="NVarChar(2000)")]
	public string Header
	{
		get
		{
			return this._Header;
		}
		set
		{
			if ((this._Header != value))
			{
				this.OnHeaderChanging(value);
				this.SendPropertyChanging();
				this._Header = value;
				this.SendPropertyChanged("Header");
				this.OnHeaderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Contents
	{
		get
		{
			return this._Contents;
		}
		set
		{
			if ((this._Contents != value))
			{
				this.OnContentsChanging(value);
				this.SendPropertyChanging();
				this._Contents = value;
				this.SendPropertyChanged("Contents");
				this.OnContentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Solution", DbType="Char(1)")]
	public System.Nullable<char> Type_Solution
	{
		get
		{
			return this._Type_Solution;
		}
		set
		{
			if ((this._Type_Solution != value))
			{
				this.OnType_SolutionChanging(value);
				this.SendPropertyChanging();
				this._Type_Solution = value;
				this.SendPropertyChanged("Type_Solution");
				this.OnType_SolutionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image_Small", DbType="NVarChar(200)")]
	public string Link_Image_Small
	{
		get
		{
			return this._Link_Image_Small;
		}
		set
		{
			if ((this._Link_Image_Small != value))
			{
				this.OnLink_Image_SmallChanging(value);
				this.SendPropertyChanging();
				this._Link_Image_Small = value;
				this.SendPropertyChanged("Link_Image_Small");
				this.OnLink_Image_SmallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image", DbType="NVarChar(200)")]
	public string Link_Image
	{
		get
		{
			return this._Link_Image;
		}
		set
		{
			if ((this._Link_Image != value))
			{
				this.OnLink_ImageChanging(value);
				this.SendPropertyChanging();
				this._Link_Image = value;
				this.SendPropertyChanged("Link_Image");
				this.OnLink_ImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poster", DbType="NVarChar(100)")]
	public string Poster
	{
		get
		{
			return this._Poster;
		}
		set
		{
			if ((this._Poster != value))
			{
				this.OnPosterChanging(value);
				this.SendPropertyChanging();
				this._Poster = value;
				this.SendPropertyChanged("Poster");
				this.OnPosterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosterID", DbType="VarChar(10)")]
	public string PosterID
	{
		get
		{
			return this._PosterID;
		}
		set
		{
			if ((this._PosterID != value))
			{
				this.OnPosterIDChanging(value);
				this.SendPropertyChanging();
				this._PosterID = value;
				this.SendPropertyChanged("PosterID");
				this.OnPosterIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creater", DbType="VarChar(10)")]
	public string Creater
	{
		get
		{
			return this._Creater;
		}
		set
		{
			if ((this._Creater != value))
			{
				this.OnCreaterChanging(value);
				this.SendPropertyChanging();
				this._Creater = value;
				this.SendPropertyChanged("Creater");
				this.OnCreaterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(14)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifier", DbType="VarChar(10)")]
	public string Modifier
	{
		get
		{
			return this._Modifier;
		}
		set
		{
			if ((this._Modifier != value))
			{
				this.OnModifierChanging(value);
				this.SendPropertyChanging();
				this._Modifier = value;
				this.SendPropertyChanged("Modifier");
				this.OnModifierChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="VarChar(14)")]
	public string ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.News")]
public partial class New : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Id;
	
	private string _Header;
	
	private string _Contents;
	
	private System.Nullable<char> _Type_News;
	
	private string _Link_Image_Small;
	
	private string _Link_Image;
	
	private string _Author;
	
	private string _Poster;
	
	private string _PosterID;
	
	private string _Creater;
	
	private string _CreateDate;
	
	private string _Modifier;
	
	private string _ModifyDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnHeaderChanging(string value);
    partial void OnHeaderChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnType_NewsChanging(System.Nullable<char> value);
    partial void OnType_NewsChanged();
    partial void OnLink_Image_SmallChanging(string value);
    partial void OnLink_Image_SmallChanged();
    partial void OnLink_ImageChanging(string value);
    partial void OnLink_ImageChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnPosterChanging(string value);
    partial void OnPosterChanged();
    partial void OnPosterIDChanging(string value);
    partial void OnPosterIDChanged();
    partial void OnCreaterChanging(string value);
    partial void OnCreaterChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnModifierChanging(string value);
    partial void OnModifierChanged();
    partial void OnModifyDateChanging(string value);
    partial void OnModifyDateChanged();
    #endregion
	
	public New()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Header", DbType="NVarChar(2000)")]
	public string Header
	{
		get
		{
			return this._Header;
		}
		set
		{
			if ((this._Header != value))
			{
				this.OnHeaderChanging(value);
				this.SendPropertyChanging();
				this._Header = value;
				this.SendPropertyChanged("Header");
				this.OnHeaderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Contents
	{
		get
		{
			return this._Contents;
		}
		set
		{
			if ((this._Contents != value))
			{
				this.OnContentsChanging(value);
				this.SendPropertyChanging();
				this._Contents = value;
				this.SendPropertyChanged("Contents");
				this.OnContentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_News", DbType="Char(1)")]
	public System.Nullable<char> Type_News
	{
		get
		{
			return this._Type_News;
		}
		set
		{
			if ((this._Type_News != value))
			{
				this.OnType_NewsChanging(value);
				this.SendPropertyChanging();
				this._Type_News = value;
				this.SendPropertyChanged("Type_News");
				this.OnType_NewsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image_Small", DbType="NVarChar(200)")]
	public string Link_Image_Small
	{
		get
		{
			return this._Link_Image_Small;
		}
		set
		{
			if ((this._Link_Image_Small != value))
			{
				this.OnLink_Image_SmallChanging(value);
				this.SendPropertyChanging();
				this._Link_Image_Small = value;
				this.SendPropertyChanged("Link_Image_Small");
				this.OnLink_Image_SmallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Image", DbType="NVarChar(200)")]
	public string Link_Image
	{
		get
		{
			return this._Link_Image;
		}
		set
		{
			if ((this._Link_Image != value))
			{
				this.OnLink_ImageChanging(value);
				this.SendPropertyChanging();
				this._Link_Image = value;
				this.SendPropertyChanged("Link_Image");
				this.OnLink_ImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(100)")]
	public string Author
	{
		get
		{
			return this._Author;
		}
		set
		{
			if ((this._Author != value))
			{
				this.OnAuthorChanging(value);
				this.SendPropertyChanging();
				this._Author = value;
				this.SendPropertyChanged("Author");
				this.OnAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poster", DbType="NVarChar(100)")]
	public string Poster
	{
		get
		{
			return this._Poster;
		}
		set
		{
			if ((this._Poster != value))
			{
				this.OnPosterChanging(value);
				this.SendPropertyChanging();
				this._Poster = value;
				this.SendPropertyChanged("Poster");
				this.OnPosterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosterID", DbType="VarChar(10)")]
	public string PosterID
	{
		get
		{
			return this._PosterID;
		}
		set
		{
			if ((this._PosterID != value))
			{
				this.OnPosterIDChanging(value);
				this.SendPropertyChanging();
				this._PosterID = value;
				this.SendPropertyChanged("PosterID");
				this.OnPosterIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creater", DbType="VarChar(10)")]
	public string Creater
	{
		get
		{
			return this._Creater;
		}
		set
		{
			if ((this._Creater != value))
			{
				this.OnCreaterChanging(value);
				this.SendPropertyChanging();
				this._Creater = value;
				this.SendPropertyChanged("Creater");
				this.OnCreaterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="VarChar(14)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifier", DbType="VarChar(10)")]
	public string Modifier
	{
		get
		{
			return this._Modifier;
		}
		set
		{
			if ((this._Modifier != value))
			{
				this.OnModifierChanging(value);
				this.SendPropertyChanging();
				this._Modifier = value;
				this.SendPropertyChanged("Modifier");
				this.OnModifierChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="VarChar(14)")]
	public string ModifyDate
	{
		get
		{
			return this._ModifyDate;
		}
		set
		{
			if ((this._ModifyDate != value))
			{
				this.OnModifyDateChanging(value);
				this.SendPropertyChanging();
				this._ModifyDate = value;
				this.SendPropertyChanged("ModifyDate");
				this.OnModifyDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
